{% set name = "datasets" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 851e2bdd453e7e53570007584459e43209b2849978f526e09b0465fbc5b4b574

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - conllu
    - dataclasses
    - dill
    - fsspec
    - importlib_metadata
    - lxml
    - multiprocess
    - numpy >=1.17
    - openpyxl
    - packaging
    - pandas
    - py7zr
    - pyarrow >=0.17.1
    - python >=3.6
    - python-xxhash
    - requests >=2.19.0
    - tqdm >=4.27,<4.50.0

test:
  imports:
    - datasets
    - datasets.commands
    - datasets.utils

about:
  home: https://github.com/huggingface/datasets
  license: Apache-2.0
  license_family: Apache
  # License file manually packaged. See: https://github.com/huggingface/datasets/pull/1007
  license_file: LICENSE
  summary: HuggingFace/Datasets is an open library of NLP datasets.
  doc_url: https://huggingface.co/docs/datasets/
  dev_url: https://github.com/huggingface/datasets

extra:
  recipe-maintainers:
    - oblute
    - Tata17
    - thewchan
    - mxr-conda
    - wietsedv
