{% set name = "datasets" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4548241548ab45a3a4259f55c9e4ea79c6b03b2445be4a5971494c1b71e35262

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.17
    - pyarrow >=0.17.1
    - python-xxhash
    - dill
    - pandas
    - requests >=2.19.0
    - tqdm >=4.27,<4.50.0
    - dataclasses
    - multiprocess
    - importlib_metadata
    - fsspec

test:
  imports:
    - datasets
    - datasets.commands
    - datasets.utils

about:
  home: https://github.com/huggingface/datasets
  license: Apache-2.0
  license_family: Apache
  # License file manually packaged. See: https://github.com/huggingface/datasets/pull/1007
  license_file: LICENSE
  summary: HuggingFace/Datasets is an open library of NLP datasets.
  doc_url: https://huggingface.co/docs/datasets/
  dev_url: https://github.com/huggingface/datasets

extra:
  recipe-maintainers:
    - oblute
    - Tata17
    - wietsedv
