{% set name = "datasets" %}
{% set version = "4.8.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: bf00b89a4074c1607bb85537a3add1c6552f12f7759b98c20cf8982eb85da567

build:
  number: 
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv
  entry_points:
    - datasets-cli=datasets.commands.datasets_cli:main
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - filelock
    - numpy >=1.17
    - pyarrow >=21.0.0
    - dill >=0.3.0,<0.4.2
    - pandas
    - requests >=2.32.2
    - httpx <1.0.0
    - tqdm >=4.66.3
    - python-xxhash
    - multiprocess <0.70.20
    # fsspec[http]
    - fsspec >=2023.1.0,<=2026.2.0
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - huggingface_hub >=0.25.0,<2.0
    - packaging
    - pyyaml >=5.1
  run_constrained:
    # AUDIO_REQUIRE
    - torchcodec >=0.6.0
    #- pytorch >=2.8.0
    # VISION_REQUIRE
    - pillow >=9.4.0
    # BENCHMARKS_REQUIRE
    #- tensorflow-base ==2.12.0
    #- pytorch ==2.0.1
    - transformers >=4.30.1
    # QUALITY_REQUIRE
    - ruff >=0.3.0
    # PDFS_REQUIRE
    - pdfplumber >=0.11.4
    # NIBABEL_REQUIRE
    - nibabel >=5.3.2
    - ipyniivue ==2.4.2
    # jax
    - jax >=0.3.14
    - jaxlib >=0.3.14
    # tensorflow_gpu
    #- tensorflow-base >=2.6.0

# Very long tests execution, run only test list from pypi:
{% set test_files = [
    "tests/test_arrow_dataset.py",
    "tests/test_arrow_reader.py",
    "tests/test_arrow_writer.py",
    "tests/test_builder.py",
    "tests/test_data_files.py",
    "tests/test_dataset_dict.py",
    "tests/test_dataset_list.py",
    "tests/test_distributed.py",
    "tests/test_download_manager.py",
    "tests/test_exceptions.py",
    "tests/test_experimental.py",
    "tests/test_extract.py",
    "tests/test_file_utils.py",
    "tests/test_filelock.py",
    "tests/test_filesystem.py",
    "tests/test_fingerprint.py",
    "tests/test_formatting.py",
    "tests/test_hub.py",
    "tests/test_info.py",
    "tests/test_info_utils.py",
    "tests/test_inspect.py",
    "tests/test_iterable_dataset.py",
    "tests/test_load.py",
    "tests/test_metadata_util.py",
    "tests/test_offline_util.py",
    "tests/test_parallel.py",
    "tests/test_patching.py",
    "tests/test_py_utils.py",
    "tests/test_search.py",
    "tests/test_sharding_utils.py",
    "tests/test_splits.py",
    "tests/test_streaming_download_manager.py",
    "tests/test_table.py",
    "tests/test_tqdm.py",
    "tests/test_upstream_hub.py",
    "tests/test_version.py"
] %}
# >   raise RuntimeError( "One of the subprocesses has abruptly died during map operation." "To debug the error, disable multiprocessing.")
# E   RuntimeError: One of the subprocesses has abruptly died during map operation.To debug the error, disable multiprocessing.
{% set deselect_tests = " --deselect=tests/test_upstream_hub.py::TestPushToHub::test_push_dataset_dict_to_hub_num_proc" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_upstream_hub.py::TestPushToHub::test_push_dataset_dict_to_hub_iterable_num_proc" %}
# >   raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
# E   TypeError: Passing coroutines is forbidden, use tasks explicitly.
{% set deselect_tests = deselect_tests + " --deselect=tests/test_distributed.py::test_torch_distributed_run" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_distributed.py::test_torch_distributed_run_streaming_with_num_workers" %}
# >   os.symlink("..", directory / "subdir", target_is_directory=True)
# E   OSError: [WinError 1314] A required privilege is not held by the client
{% set deselect_tests = deselect_tests + " --deselect=tests/test_extract.py::test_tar_extract_insecure_files" %}  # [win]

# pytorch is not available for python 3.14
{% set deselect_tests = deselect_tests + " --deselect=tests/test_arrow_dataset.py" %}  # [py==314]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_iterable_dataset.py" %}  # [py==314]
# >       assert builder.cache_dir == builder_cache_dir.as_posix()  # old cache from 2.1
# E       AssertionError: assert '/tmp/pytest-...04e3ac03a13a5' == '/tmp/pytest-...6925d64deea5d'
{% set deselect_tests = deselect_tests + " --deselect=tests/test_load.py" %}  # [py==314]

# Skip tests that are failing on the CI.
# requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://hub-ci.huggingface.co/api/repos/create
{% set deselect_tests = deselect_tests + " --deselect=tests/test_file_utils.py" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_inspect.py" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_load.py" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_upstream_hub.py" %}

# E   ValueError: Compression type zstd not supported
{% set deselect_tests = deselect_tests + " --deselect=tests/test_filesystem.py::test_compression_filesystems" %}  # [py<314]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_streaming_download_manager.py::test_streaming_dl_manager_extract_all_supported_single_file_compression_types" %}  # [py<314]

# E   AttributeError: module 'subprocess' has no attribute '_USE_VFORK'
{% set deselect_tests = deselect_tests + " --deselect=tests/test_dataset_dict.py::DatasetDictTest::test_serialization" %}  # [py==314]

test:
  source_files:
    - tests
    - src
  imports:
    - datasets
    - datasets.commands
    - datasets.utils
    - datasets.arrow_dataset
    - datasets.arrow_reader
    - datasets.arrow_writer
    - datasets.builder
    - datasets.combine
    - datasets.config
    - datasets.data_files
    - datasets.dataset_dict
    - datasets.distributed
    - datasets.download
    - datasets.exceptions
    - datasets.features
    - datasets.filesystems
    - datasets.fingerprint
    - datasets.formatting
    - datasets.hub
    - datasets.info
    - datasets.inspect
    - datasets.io
    - datasets.iterable_dataset
    - datasets.load
    - datasets.naming
    - datasets.packaged_modules
    - datasets.parallel
    - datasets.search
    - datasets.splits
    - datasets.streaming
    - datasets.table
  requires:
    - absl-py
    - decorator
    - openjdk 17.*
    - pillow >=9.4.0
    - pip
    - pyspark >=3.4
    - pytest
    - zstandard
    # tests/utils.py:10: in <module>
    # from distutils.util import strtobool
    # E   ModuleNotFoundError: No module named 'distutils'
    - setuptools  # [py==314]
    # Remove constraints on these packages when they will be available for Python 3.14 on the main channel.
    - h5py  # [py<314]
    - pytorch-cpu  # [py<314]
  commands:
    - pip check
    - datasets-cli --help
    - pytest -v {{ test_files | join(' ') }} {{ deselect_tests }}

about:
  home: https://github.com/huggingface/datasets
  summary: HuggingFace community-driven open-source library of datasets
  description: |
    Datasets is a lightweight library providing two main features:

    - one-line dataloaders for many public datasets: one-liners to download and pre-process any of the number of datasets major public datasets (text datasets in 467 languages and dialects, image datasets, audio datasets, etc.) provided on the HuggingFace Datasets Hub. With a simple command like squad_dataset = load_dataset("squad"), get any of these datasets ready to use in a dataloader for training/evaluating a ML model (Numpy/Pandas/PyTorch/TensorFlow/JAX),
    - efficient data pre-processing: simple, fast and reproducible data pre-processing for the above public datasets as well as your own local datasets in CSV/JSON/text/PNG/JPEG/etc. With simple commands like `processed_dataset = dataset.map(process_example)`, efficiently prepare the dataset for inspection and ML model evaluation and training.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE  
  doc_url: https://huggingface.co/docs/datasets/index
  dev_url: https://github.com/huggingface/datasets

extra:
  recipe-maintainers:
    - oblute
    - Tata17
    - thewchan
    - mxr-conda
    - wietsedv
